### ISSUE TITLE
Не показываются запросы тразакции

### ISSUE THREAD

**Issue by maxnag** [Alert/profilertoolbar#10]
Делаю так:

Database::instance()->begin();

что-то делаю с запросами в блоке try ...catch...

затем или Database::instance()->commit(); или Database::instance()->rollback();

юзаю mysql драйвер, в сводке запросов нет отображения об управляющих запросах транзакции.

Для наглядности желательно поставить.

**Comment by Alert** [comment]
Добавил вывод управляющих запросов транзакций.
Но к сожалению решение не идеальное так как данные о запросах я получаю из штатного Profiler, а он группирует одинаковые запросы. При нескольких транзакциях, запросы будут выводится в неправильном порядке.
Пока не уверен что это очень важный функционал, но если будет востребован, то придется отказаться от Profiler и писать польностью свой сбор и получение запросов.

**Comment by maxnag** [comment]
Отлично, спасибо большое, мне особо и не надо последовательность показа запросов транзакция, но видеть их очень надо!!!! Спасибо еще раз!
ЗЫ Понравилось перекрытие эксепшенов в стиле профайлера!
