### ISSUE TITLE
Предложение по улучшению

### ISSUE THREAD

**Issue by maxnag** [Alert/profilertoolbar#11]
Иногда при разработке необходимо знать какие у класса (библиотеки) есть публичные методы, и прочее. В данный момент можно в IDE Eclipse нажать ctrl+O и посмотреть список всем методов текущего класса, но у родителей не глянешь, и других классов тоже. Для просмотра я юзаю старую либу Dbug (http://dbug.ospinto.com/) она как раз показывает, всё что нужно у любого класса, экземпляр которого передан в неё.

Что если сделать и тут такое, кидаешь переменную и показывает. Такое конечно в профайлере уже есть, но там что-то типа var_dump с недружественным просмотром данных и показом всего, причем и значений переменных. Может обсудим?

**Comment by Alert** [comment]
Честно говоря не вижу смысла как-то кастомизировать дамп переменных.
По моему, штатный var_dump очень удобно выводит информацию.

**Comment by maxnag** [comment]
Окей, вот дамп объекта модуля авторизации, который помещается в сессию после успешного логина

object(Model_User)#30 (37) {
  ["_has_one":protected] => array(1) {
    ["user_info"] => array(2) {
      ["model"] => string(9) "usersinfo"
      ["foreign_key"] => string(7) "user_id"
    }
  }
  ["rules"] => array(0) {
  }
  ["filters"] => array(0) {
  }
  ["labels"] => array(0) {
  }
  ["_has_many":protected] => array(2) {
    ["user_tokens"] => array(4) {
      ["model"] => string(10) "user_token"
      ["foreign_key"] => string(7) "user_id"
      ["through"] => NULL
      ["far_key"] => string(13) "user_token_id"
    }
    ["roles"] => array(4) {
      ["model"] => string(4) "role"
      ["foreign_key"] => string(7) "user_id"
      ["through"] => string(11) "roles_users"
      ["far_key"] => string(7) "role_id"
    }
  }
  ["_belongs_to":protected] => array(0) {
  }
  ["_load_with":protected] => array(0) {
  }
  ["_validation":protected] => NULL
  ["_object":protected] => array(8) {
    ["id"] => string(1) "1"
    ["email"] => string(14) "some@emai.com"
    ["username"] => string(14) "some@emai.com"
    ["password"] => string(32) "223aee2c160c395c6bc1dfd2b4e6c7e0"
    ["main_role"] => string(1) "2"
    ["logins"] => string(3) "130"
    ["last_login"] => string(10) "1332237882"
    ["show"] => string(1) "1"
  }
  ["_changed":protected] => array(0) {
  }
  ["_original_values":protected] => array(8) {
    ["id"] => string(1) "1"
    ["email"] => string(14) "some@emai.com"
    ["username"] => string(14) "some@emai.com"
    ["password"] => string(32) "223aee2c160c395c6bc1dfd2b4e6c7e0"
    ["main_role"] => string(1) "2"
    ["logins"] => string(3) "130"
    ["last_login"] => string(10) "1332237882"
    ["show"] => string(1) "1"
  }
  ["_related":protected] => array(0) {
  }
  ["_valid":protected] => bool(true)
  ["_loaded":protected] => bool(true)
  ["_saved":protected] => bool(true)
  ["_sorting":protected] => NULL
  ["_foreign_key_suffix":protected] => string(3) "_id"
  ["_object_name":protected] => string(4) "user"
  ["_object_plural":protected] => string(5) "users"
  ["_table_name":protected] => string(5) "users"
  ["_table_columns":protected] => array(8) {
    ["id"] => array(13) {
      ["type"] => string(3) "int"
      ["min"] => string(1) "0"
      ["max"] => string(10) "4294967295"
      ["column_name"] => string(2) "id"
      ["column_default"] => NULL
      ["data_type"] => string(12) "int unsigned"
      ["is_nullable"] => bool(false)
      ["ordinal_position"] => int(1)
      ["display"] => string(2) "11"
      ["comment"] => string(0) ""
      ["extra"] => string(14) "auto_increment"
      ["key"] => string(3) "PRI"
      ["privileges"] => string(31) "select,insert,update,references"
    }
    ["email"] => array(12) {
      ["type"] => string(6) "string"
      ["column_name"] => string(5) "email"
      ["column_default"] => NULL
      ["data_type"] => string(7) "varchar"
      ["is_nullable"] => bool(false)
      ["ordinal_position"] => int(2)
      ["character_maximum_length"] => string(3) "254"
      ["collation_name"] => string(15) "utf8_general_ci"
      ["comment"] => string(0) ""
      ["extra"] => string(0) ""
      ["key"] => string(3) "UNI"
      ["privileges"] => string(31) "select,insert,update,references"
    }
    ["username"] => array(12) {
      ["type"] => string(6) "string"
      ["column_name"] => string(8) "username"
      ["column_default"] => string(0) ""
      ["data_type"] => string(7) "varchar"
      ["is_nullable"] => bool(false)
      ["ordinal_position"] => int(3)
      ["character_maximum_length"] => string(2) "32"
      ["collation_name"] => string(15) "utf8_general_ci"
      ["comment"] => string(0) ""
      ["extra"] => string(0) ""
      ["key"] => string(3) "UNI"
      ["privileges"] => string(31) "select,insert,update,references"
    }
    ["password"] => array(12) {
      ["type"] => string(6) "string"
      ["column_name"] => string(8) "password"
      ["column_default"] => NULL
      ["data_type"] => string(7) "varchar"
      ["is_nullable"] => bool(false)
      ["ordinal_position"] => int(4)
      ["character_maximum_length"] => string(2) "64"
      ["collation_name"] => string(15) "utf8_general_ci"
      ["comment"] => string(0) ""
      ["extra"] => string(0) ""
      ["key"] => string(0) ""
      ["privileges"] => string(31) "select,insert,update,references"
    }
    ["main_role"] => array(13) {
      ["type"] => string(3) "int"
      ["min"] => string(11) "-2147483648"
      ["max"] => string(10) "2147483647"
      ["column_name"] => string(9) "main_role"
      ["column_default"] => string(1) "1"
      ["data_type"] => string(3) "int"
      ["is_nullable"] => bool(false)
      ["ordinal_position"] => int(5)
      ["display"] => string(2) "11"
      ["comment"] => string(0) ""
      ["extra"] => string(0) ""
      ["key"] => string(0) ""
      ["privileges"] => string(31) "select,insert,update,references"
    }
    ["logins"] => array(13) {
      ["type"] => string(3) "int"
      ["min"] => string(1) "0"
      ["max"] => string(10) "4294967295"
      ["column_name"] => string(6) "logins"
      ["column_default"] => string(1) "0"
      ["data_type"] => string(12) "int unsigned"
      ["is_nullable"] => bool(false)
      ["ordinal_position"] => int(6)
      ["display"] => string(2) "10"
      ["comment"] => string(0) ""
      ["extra"] => string(0) ""
      ["key"] => string(0) ""
      ["privileges"] => string(31) "select,insert,update,references"
    }
    ["last_login"] => array(13) {
      ["type"] => string(3) "int"
      ["min"] => string(1) "0"
      ["max"] => string(10) "4294967295"
      ["column_name"] => string(10) "last_login"
      ["column_default"] => NULL
      ["data_type"] => string(12) "int unsigned"
      ["is_nullable"] => bool(true)
      ["ordinal_position"] => int(7)
      ["display"] => string(2) "10"
      ["comment"] => string(0) ""
      ["extra"] => string(0) ""
      ["key"] => string(0) ""
      ["privileges"] => string(31) "select,insert,update,references"
    }
    ["show"] => array(13) {
      ["type"] => string(3) "int"
      ["min"] => string(4) "-128"
      ["max"] => string(3) "127"
      ["column_name"] => string(4) "show"
      ["column_default"] => string(1) "1"
      ["data_type"] => string(7) "tinyint"
      ["is_nullable"] => bool(true)
      ["ordinal_position"] => int(8)
      ["display"] => string(1) "1"
      ["comment"] => string(0) ""
      ["extra"] => string(0) ""
      ["key"] => string(0) ""
      ["privileges"] => string(31) "select,insert,update,references"
    }
  }
  ["_updated_column":protected] => NULL
  ["_created_column":protected] => NULL
  ["_serialize_columns":protected] => array(0) {
  }
  ["_primary_key":protected] => string(2) "id"
  ["_primary_key_value":protected] => string(1) "1"
  ["_table_names_plural":protected] => bool(true)
  ["_reload_on_wakeup":protected] => bool(true)
  ["_db":protected] => object(Database_MySQL)#16 (6) {
    ["_connection_id":protected] => string(40) "e12175ec983f0465854781dfd31fdeb143884aaf"
    ["_identifier":protected] => string(1) "`"
    ["last_query"] => string(101) "SELECT COUNT(*) AS`records_found`FROM`gv_roles_users`WHERE`user_id`= '1' AND`role_id` IN ('3')"
    ["_instance":protected] => string(7) "default"
    ["_connection":protected] => resource(4) of type (mysql link)
    ["_config":protected] => array(6) {
      ["type"] => string(5) "mysql"
      ["connection"] => array(3) {
        ["hostname"] => string(9) "localhost"
        ["database"] => string(20) "nagaychen_genvik_crm"
        ["persistent"] => bool(false)
      }
      ["table_prefix"] => string(3) "gv_"
      ["charset"] => string(4) "utf8"
      ["caching"] => bool(false)
      ["profiling"] => bool(true)
    }
  }
  ["_db_group":protected] => NULL
  ["_db_applied":protected] => array(0) {
  }
  ["_db_pending":protected] => array(0) {
  }
  ["_db_reset":protected] => bool(true)
  ["_db_builder":protected] => NULL
  ["_with_applied":protected] => array(0) {
  }
  ["_cast_data":protected] => array(0) {
  }
  ["_errors_filename":protected] => string(4) "user"
}

Я например не вижу здесь методов класса ORM find(), find_all, и тд, но зато есть какие-то частичные протектные методы.

**Comment by Alert** [comment]
А зачем их видеть в дампе?
Это же нужно только при кодинге в самой IDE.
