### ISSUE TITLE
Не выводятся пользовательские данные

### ISSUE THREAD

**Issue by TSka** [Alert/profilertoolbar#12]
Если в настройках включен файрбаг, то в html не выводятся пользовательские данные, $_CUSTOM пустая.

**Comment by Alert** [comment]
Протестировал, вроде всё нормально выводится при включенном и выключенном firebug.
У Вас версия ProfilerToolbar 0.2.4?
Опишите какие данные передаете в ProfilerToolbar::addData();

**Comment by TSka** [comment]
О, простите, разобрался. 

parent::after() в моем контроллере стоял в начале метода after(){...}, поэтому ProfilerToolbar::firebug() выполнялся раньше, чем ProfilerToolbar::addData()

**Comment by Alert** [comment]
Ok
