### ISSUE TITLE
Проблема модуля подсветки с модулем SUHOSIN

### ISSUE THREAD

**Issue by maxnag** [Alert/profilertoolbar#13]
Решил поставить модулья на свой хостинг, в результате выдал ошибку

ErrorException [ Fatal Error ]
SUHOSIN - Use of preg_replace() with /e modifier is forbidden by configuration

MODPATH/profilertoolbar/vendor/geshi/geshi.php(2148) : regexp code [ 2148 ]

```
{PHP internal call} » Kohana_Core::shutdown_handler ( arguments )
0   /([^a-zA-Z0-9$_\|\#;>|^])(return)(?=[^a-zA-Z0-9_<\|%\-&])/ie
1   '\1' . $this->add_url_to_keyword('\2', '1', 'BEGIN') . '<|/1/>' . $this->change_case('\2') . '|>' . $this->add_url_to_keyword('\2', '1', 'END')
2   * * @return void */ public function action_index() { <|!REG3XP0!>$date|> = <|!REG3XP0!>$this|>-&gt;reuest-&gt;param( 
```

Пришлось отключить подсветку

**Comment by Alert** [comment]
Это проблема в стороннем модуле подсветки кода [geshi](http://qbnz.com/highlighter/).  Менять код в ней будет не лучшим решением.
Я бы вам посоветовал разрешить все параметры регулярных выражений в SUHOSIN (если он это позволяет).
А вообще мне кажется лучше полностью отключить SUHOSIN, так как толку от него мало :)
