### ISSUE TITLE
SELECT FOUND_ROWS() возвращает 0

### ISSUE THREAD

**Issue by iotch** [Alert/profilertoolbar#18]
При включенном profilertoolbar FOUND_ROWS() возвращает некорректные результаты, например:

dummytable - любая непустая таблица

<pre>
DB::query(Database::SELECT, "SELECT SQL_CALC_FOUND_ROWS * FROM dummytable")->execute()->as_array();
DB::query(Database::SELECT, "SELECT FOUND_ROWS() AS found")->execute()->get('found');
</pre>

Второй запрос всегда возвращает 0.

**Comment by Alert** [comment]
Спасибо за багрепорт.
Поправил, проверяй.

**Comment by iotch** [comment]
Да, теперь ОК, спасибо. Правда, для запроса с SQL_CALC_FOUND_ROWS нет EXPLAIN.
Я сделал свой довольно грязный хак - добавил еще одно соединение в  /profilertoolbar/classes/kohana/database/mysql.php

<pre>
            if ($persistent)
            {
                // Create a persistent connection
                $this->_connection = mysql_pconnect($hostname, $username, $password);
                $this->_connection_alt = mysql_pconnect($hostname, $username, $password, TRUE);
            }
            else
            {
                // Create a connection and force it to be a new link
                $this->_connection = mysql_connect($hostname, $username, $password, TRUE);
                $this->_connection_alt = mysql_connect($hostname, $username, $password, TRUE);
            }
</pre>

 ... + еще в нескольких соответствующих местах.

и в обработке SELECT теперь альтернативное соединение:

<pre>
          $_sql = trim($sql);
          if(stripos($_sql,'select') === 0){
            if(($expl = mysql_query('EXPLAIN '.$_sql,$this->_connection_alt)) !== false){
              $expl = new Database_MySQL_Result($expl,$sql, false);
            }
            ProfilerToolbar::setSqlData($this->_instance,$sql,$res->count(),$expl->as_array());
          }
</pre>

Т.е. для EXPLAIN делается отдельный запрос к БД. 
Грязно конечно, но это работает.

**Comment by Alert** [comment]
А почему нет EXPLAIN для SQL_CALC_FOUND_ROWS ?
У меня выводится. 
![Swipe View](http://s2.hostingkartinok.com/uploads/images/2012/09/f54dd0153b49a8506b10a9c91e1553a7.png)
Напиши пожалуйста пример своего запроса.

**Comment by iotch** [comment]
Да, прошу прощения, EXPLAIN на месте, похоже просто не заметил...

**Comment by Alert** [comment]
ok
