### ISSUE TITLE
Несовместимость с Kohana 3.3

### ISSUE THREAD

**Issue by RomeroMsk** [Alert/profilertoolbar#25]
При попытке использовать модуль в Kohana 3.3 получаю массу ошибок: undefined variable $test во вьюхе error, передача multibyte sequence в htmlspecialchars и т.д.
Можно ли обновить модуль под последнюю версию фреймворка?

**Comment by Invision70** [comment]
profilertoolbar для Kohana 3.3 http://habrahabr.ru/sandbox/70146/

**Comment by EvgeniyRRU** [comment]
Тут пулл-реквест даже есть. Но на репозиторий забили(

**Comment by Alert** [comment]
Спасибо что помните и пользуетесь данным модулем. Воскрешу работу над ним в течении месяца.

**Comment by Invision70** [comment]
Хороший модуль получился, спасибо.

**Comment by workpro** [comment]
Да!! воскрешайте!!
