### ISSUE TITLE
There is no need for overwriting the Kohana Database Class

### ISSUE THREAD

**Issue by nexeck** [Alert/profilertoolbar#3]
You can get the queries from the database Profiler
Like here: https://github.com/biakaveron/debug-toolbar/blob/3.2/classes/kohana/debugtoolbar.php (get_queries function)

**Comment by Alert** [comment]
I overrite Database Class for get EXPLAIN select queries and get count rows for each query

**Comment by nexeck** [comment]
Okay, than you cant just get it from the profiler
