### ISSUE TITLE
Ошибка при выводе переменных

### ISSUE THREAD

**Issue by leshyi** [Alert/profilertoolbar#32]
ProfilerToolbar::addData('sql tab',$requests);
выдает ошибку.
ProfilerToolbar::addData($requests);
работает

Kohana 3.3.2 stable

**Comment by Alert** [comment]
Всё правильно. Название таба идёт [вторым параметром](https://github.com/Alert/profilertoolbar/blob/3.3/master/classes/Kohana/ProfilerToolbar.php#L526).
