### ISSUE TITLE
Ошибка вывода результатов sql

### ISSUE THREAD

**Issue by leshyi** [Alert/profilertoolbar#33]
При любом запросе sql ошибка в функции
public static function setSqlData($instance, $sql, $rows = null) {
    self::$_SQL[$instance][$sql] = array(
      'rows'    => $rows,
      'explain' => null,
    );
  }

Kohana 3.3.2

**Comment by Alert** [comment]
Не удаётся воспроизвести ошибку.
Такой код работает нормально. Если будет повторяться, опишите проблему подробнее.

``` php
    $res = DB::select('* FROM users')->execute();
    $res = DB::query(Database::SELECT,'select * FROM users WHERE id=10')->execute();
    $res = DB::query(Database::SELECT,'select * FROM users LIMIT 10')->execute();
```
