### ISSUE TITLE
Неверный вывод  путей файлов

### ISSUE THREAD

**Issue by TSka** [Alert/profilertoolbar#6]
У меня директории коханы (modules, system) расположены вне директории домена, т.к. используются для нескольких проектов. Т.е. application в /home/admin/tmp_profiletoolbar, а modules и system в /home/admin/kohana. Поэтому при выводе путей к файлам получается такая околесица: http://i.imgur.com/wACeH.png

В views/PTB/items/files.php:21 из пути файла просто отбрасывается количество символов в DOCROOT

**Comment by Alert** [comment]
Исправил. Сегодня сделаю коммит новой версии.
Затестируй потом пожалуйста. Решение не идеальное, но должно устроить.

**Comment by TSka** [comment]
Ну все красиво сейчас
