### ISSUE TITLE
поддержка Jelly

### ISSUE THREAD

**Issue by svsool** [Alert/profilertoolbar#9]
Добавьте пожалуйста как будет время поддержку ORM Jelly, он для выборки базы использует родной database https://github.com/creatoro/jelly вот его последний форк для kohana 3.2

**Comment by Alert** [comment]
Тоесть все SELECT отображаются, а UPDATE, DELETE игнорируются?

**Comment by svsool** [comment]
SELECT тоже от jelly почему то не отображаются, сам не пойму почему

**Comment by svsool** [comment]
вот метод отвечающий за SELECT https://github.com/creatoro/jelly/blob/3.2/master/classes/jelly/core/builder.php#L152, profiling в конфиге database в TRUE стоит

**Comment by Alert** [comment]
Проверил сейчас все виды запросов. Всё работает нормально, они отображаются.
Смотри включен ли у тебя профайлинг в **bootstrap.php** и в **config/database.php**

**Comment by svsool** [comment]
опс пардон, в bootsrap забыл 'profiling' => TRUE, спасибо

**Comment by svsool** [comment]
все равно не работает, взгляните вывел profiling нативный, там видно что делается select из date, а в тулбаре не отображается
http://rghost.ru/37029405/image.png

**Comment by Alert** [comment]
Попробуй дебагом пройтись, может у тебя некоторые запросы в обход стандартной _Database_ идут.

**Comment by svsool** [comment]
самый стандартный запрос Jelly::query('date')->select(), вообще никак не отображается в toolbar,
в setSqlData запрос есть http://higgs.rghost.ru/37030113.image, а вот в getSql его уже нет http://plasmon.rghost.ru/37030126.image

**Comment by Alert** [comment]
Я тестирую таким кодом:

``` php
<?php 
  Jelly::factory('art')->set(array('title'=>'new'))->save();
  Jelly::factory('art')->set(array('title'=>'new2'))->save();
  Jelly::query('art')->select();
  Jelly::factory('art',22)->set(array('title'=>'changed'))->save();
  Jelly::factory('art',23)->delete();
```

Все запросы выводятся http://rghost.ru/37031734/image.png

**Comment by svsool** [comment]
cтранно, у меня код идентичный вашему и ничего не выводится, даже нативный запрос

``` php
<?php
 DB::query(Database::SELECT, 'SELECT * FROM dates')->execute(); 
?>
```

никак не отображается, хотя в логах профайлинга он есть, идиотизм какой-то, щас попробовал наследоваться от не базового контроллера своего, все тоже заработало, значит что то у меня в базовом контроллере не так, будем искать

**Comment by svsool** [comment]
нашел в чем проблема, я передаю виджеты в главный layout таким способом, 

``` php
<?
$tickettop = Request::factory('widgets/tickettop')->execute();
$articles = Request::factory('widgets/articles')->execute();
$this->template->block_center = array($tickettop, $articles);
?>
```

соотвественно каждый виджет делает свою выборку по базе, так вот если подругажать только один виджет на страницу, toolbar работает и показывает запрос который делает виджет к базе, а если подргужать несколько виджетов как в примере выше, то запросы в тулбар не выводятся, хотя в профайлере они логируются, <?php ProfilerToolbar::render(true); ?> вывожу в главном layout перед закрывающим тегом body, попробуйте сами создайте пару тестовых контролеров наследуемых от главного, которые делают выборку по базе и подгрузите их в  layout главного контроллера

**Comment by Alert** [comment]
Аааа, понял :)
Модуль пока не поддерживает HMVC. У меня в TODO уже висит задача на счет этого, так что в скором времени сделаю)

**Comment by Alert** [comment]
Кстати хоть и есть проблемы с HMVC, но запросы всё равно должны все отображаться (уже тестил на одном проекте).
Ну я примерно понял что можно потестить, если найду баги - напишу.

**Comment by svsool** [comment]
https://github.com/svsool/toolbartest попробуйте вот это потестить, увидите что в тулбар добавляются только запросы от последнего подгруженного виджета, а в профайлинге все ок, как не странно

**Comment by Alert** [comment]
Добавь файл со структурой таблиц в бд

**Comment by svsool** [comment]
https://github.com/svsool/toolbartest/blob/master/data.sql

**Comment by Alert** [comment]
Пофиксил.
Как я и предполагал, проблема была не в Jelly, а в принципе получения данных при HMVC.
